openapi: 3.0.3
info:
  title: PanoramaEd API
  description: REST API to search colleges globally.
  version: 'v1.0'
servers: [
    {
      url: "https://localhost:8080",
      description: "Development server"
    }]
paths:
# api to fetch colleges
  /colleges:  
    get:
      description: "Returns all colleges under the filter"
      operationId: "search-college"
      parameters: 
        - name: "name"
          in: "query"
          required: false
          example: "Northeastern Univerity"
          schema:
            type: string
        - name: "course"
          in: "query"
          required: false
          example: "ComputerScience"
          schema: 
            type: string
        - name: "country"
          in: "query"
          required: false
          example: "US"
          schema:
            type: string
      responses: 
        "200":
          description:  "Successful search"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/College"
        
        "401":
          description: "Unauthenticated request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: "Not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /colleges/{college}/{course}:
    put:
      description: "Updates the upcoming events under a program"
      operationId: "update-program-content"
      parameters: 
        - name: "college"
          in: "path"
          required: true
          example: "Northeastern Univerity"
          schema:
            type: string
        - name: "course"
          in: "path"
          required: true
          example: "ComputerScience"
          schema: 
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Event"
      responses: 
        "200":
          description:  "Successful update"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Program"
        "401":
          description: "Unauthenticated request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: "Not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: "Forbidden request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      description: "deletes the events under a program"
      operationId: "delete-program-content"
      parameters: 
        - name: "college"
          in: "path"
          required: true
          example: "Northeastern Univerity"
          schema:
            type: string
        - name: "course"
          in: "path"
          required: true
          example: "ComputerScience"
          schema: 
            type: string
      responses: 
        "200":
          description:  "Successful update"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Program"
        "401":
          description: "Unauthenticated request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: "Not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: "Forbidden request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /colleges/{course}:
    get:
      description: "returns the colleges under student qualification"
      operationId: "search-gettable-colleges"
      parameters: 
        - name: "course"
          in: "path"
          required: true
          example: "ComputerScience"
          schema:
            type: string
        - name: "gre"
          in: "query"
          required: false
          example: 329
          schema: 
            type: string
        - name: "toefl"
          in: "query"
          required: false
          example: 100
          schema:
            type: string
        - name: "ielts"
          in: "query"
          required: false
          example: 7
          schema:
            type: string
      responses: 
        "200":
          description:  "Successful update"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Program"
        "401":
          description: "Unauthenticated request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: "Not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: "Forbidden request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
                
# write rest of the apis from here
                
# schema models
components:
  schemas:
    College:
      type: object
      properties:
        id:
          type: string
          example: sgdn-243n4-242fsf
        
        name:
          type: string
          example: Northeastern University
        ranking:
          type: string
          example: 25
        state:
          type: string
          example: Massachusetts
        yearEstd:
          type: string
          example: 1898
        country:
          type: string
          example: United States
        programs:
          type: array
          items:
            $ref: "#/components/schemas/Program"
        followers:
          type: string
          example: 43k
    Program:
      type: object
      properties:
        id:
          type: string
          example: sgdn-243n4-242fsf
        name:
          type: string
          example: Software Engineering Systems
        ranking:
          type: string
          example: 11
        university:
          type: string
          example: Northeastern University
        requirements:
          $ref: "#/components/schemas/ProgramRequirements"
        upcomingEvents:
          type: array
          items:
            $ref: "#/components/schemas/Event"
        fee: 
          type: string
          example: $53k
        costOfStudy:
          type: string
          enum: 
            - Premium
            - Moderate
            - Reasonable
          example: Moderate
    Event:
      type: object
      properties:
        link:
          type: string
          example: "https://zoom.us/j/5551112222"
        videoUrl:
          type: string
          format: uri
        title:
          type: string
          example: Applications of AI
        time:
          type: string
          example: "2023-11-12T13:14:157"
        duration:
          type: string
          example: "45min"
    ProgramRequirements:
      type: object
      properties:
        greScore:
          type: string
          example: 295
        ieltsScore:
          type: string
          example: 7
        toeflScore: 
          type: string
          example: 90
        cgpa:
          type: string
          example: 3.0
    Error:
      type: object
      properties:
        error:
          type: object
          example: "User not authenticated"
            
      
    