openapi: 3.1.0
info: 
  title: Student Post API
  description: REST API to fetch the student posts
  version: 'v1.0'


servers: 
  - url: http://localhost:8080

paths: 
  /posts:
    get: 
      operationId: display-posts
      description: display student posts

      responses:
        "200":
          description: successful search
          content:
            application/json:
              schema:
                type: array 
                items:
                  $ref: "#/components/schemas/Post"

        "401":
          description: Unauthenticated request
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"

        "404":
          description: "Not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Post:
      type: object
      properties:
        feedId:
          type: string
          examples:
            - skp-243n4-242fdk
        author:
          type: string
          examples:
            - skl-243m4-242fdm

        Text:
          type: string 
          examples: 
            - "Please help me with collges i can get for my GPA"

        upVote:
          type: integer
          examples: 
            - 6
    Error:
      type: object
      properties:
        code:
          type: string
          description: Error code
          examples:
            - AuthenticationError
        message:
          tyepe: string
          description: Error message
          examples:
            - User is not authenticated